#!/usr/bin/perl -w
use strict;

# requires carmel in path

# STDIN: word f1=a f2=b
# arg1 (from SRI) cipherclass: CLASS-00004 0.425734 to
# arg2 plain->cipher class channel (carmel WFST): 
# 0
# (0 (0 CLASS-00037 CLASS-00004 7.2048590358686e-05) ... )

# if arg2 is omitted, then identity class channel

# STDOUT : word f1=a f2=b CLASS-05=.425 CLASS-06=.5

my $floor=$ENV{FLOOR}; # anything below this is skipped

my $cipherclass=shift;
my $channel=shift;

die unless defined $cipherclass;

my %chan;
my %cipherclass;

if ($channel) {
open C,"carmel -DHJ $channel|" or die;
my $final=<C>;
while (<C>) {
    if (/^\(\S+ \(\S+ (\S+) (\S+) ([^)]+)\)\)$/) {
        my ($pc,$cc,$w)=($1,$2,$3);
#        print STDERR"$pc -> $cc ($w)\n";
        next if defined $floor && $w < $floor;
#        push $chan{$cc},[$pc,$w];
        $chan{$cc}.=" $pc=$w";
    }
}
close C;
}

open D,"<",$cipherclass or die;
while(<D>) {
    my ($class,$p,$w)=split;
#    print STDERR "$w : $class\n";
    $cipherclass{$w}=$class;
}

while(<>) {
    chomp;
    my ($w)=split ' ',$_,2;
    my $cc=$cipherclass{$w};
    die "$w wasn't listed in cipher classes dictionary $cipherclass" unless defined $cc;
    print $_;
    if ($channel) {
        die "cipherclass $cc for word $w wasn't in plain->cipher channel $channel" unless exists $chan{$cc};
        print $chan{$cc};
    } else {
        print " $cc=1";
    }
    print "\n";
}
