#!/bin/bash
if [[ $CONSOLE ]] ; then
    exec /usr/bin/emacs -nw "$@"
else
    emacsapp=/Applications/Emacs.app/Contents/MacOS/
    emacssrv=$emacsapp/Emacs
    exec $emacsapp/bin/emacsclient -a $emacssrv "$@"
fi
