#!/bin/bash
case $(uname) in
    Darwin)
        lwarch=Apple
        ;;
    Linux)
        lwarch=FC12
        shopt -s globstar || true
        ;;
    *)
        lwarch=Windows ;;
esac

if [[ $lwarch = Windows ]] ; then
    emacscli=emacsclient
    emacssrv=Emacs
else
    emacsapp=/Applications/Emacs.app/Contents/MacOS/
    emacscli=$emacsapp/bin/emacsclient
    emacssrv=$emacsapp/Emacs
fi

if [[ $CONSOLE ]] ; then
    exec /usr/bin/emacs -nw "$@"
else
    exec $emacscli -a $emacssrv "$@"
fi
