#!/bin/bash
if [[ $CONSOLE ]] ; then
    exec /usr/bin/emacs -nw "$@"
else
    emacsapp=/Applications/Emacs.app/Contents/MacOS/
    emacssrv=$emacsapp/Emacs
    if [[ -x ~/bin/eclient.sh ]] ; then
        exec ~/bin/eclient.sh "$@"
    else
        exec $emacsapp/bin/emacsclient -a $emacssrv "$@"
    fi
fi
