#!/usr/bin/env python2.7
usage="""
(from file weights) take weight vector, print number of features starting with pre with abs(weight)>=epsilon
"""
from graehl import *
from dumpx import *
def main(pre='',epsilon=1e-5,weights='-'):
    l=firstline(weights)
    w=str2weights(l)
    wfilt=dict((f,v) for (f,v) in w.items() if v>=epsilon)
    dump(wfilt)
    print len(wfilt),"\n"

import optfunc
optfunc.main(main)

