#!/bin/bash
BLOBS=${BLOBS:-~graehl/blobs}
. $BLOBS/bashlib/unstable/bashlib.sh

iomapred=$BLOBS/hadoop/unstable/iomr-hadoop
[[ -x $iomapred ]] || iomapred=`which iomr-hadoop`

usage() {
    cat << EOF
usage: $0 in(etrees) [out(pcfg events]

etrees are same format as input to extract (radu, heads, score 0.0)

format of output events:
LHS, TAB, CHILD1 CHILD2 ... CHILDN, TAB, count, TAB, sum(lhs count), NEWLINE

out is grouped by event.
EOF
    exit 1
}

main() {
        set -e
        bind=${bind:-`abspath $d`}
        sumsmap=$bind/lhs-sums-map
        sumsmap=$bind/fast-lhs-sums-map

        in=$1
        out=$2
#        shift
#        shift
        [[ $in ]] || usage
        inbase=${in%.eng-parse}
        showvars_optional inbase predot
        predot=${predot:-$inbase}
        pre=${pre:-$predot.}
        counted=${counted:-${pre}counted}
        sums=${sums:-${pre}lhs-sums}
        out=${out:-${pre}for-norm}
        showvars_required in out counted sums
        showvars_optional infs pre start_at

        nostepexit=1
        infs=$infs outfs= step 1 iomr-hadoop "$in" "$counted" $bind/pcfg-map $bind/count.py

        infs= outfs= step 2 iomr-hadoop "$counted" "$sums" $sumsmap $bind/count.py

        hadget "$sums"

        showvars_required out
        catdiv=$bind/cat-pcfg-for-divide

        infs= outfs=$out step 3 iomr-hadoop "$counted" "$out" "$catdiv $sums" NONE

        hadpreview "$out"
    }

main "$@";exit

#        if [[ $local || $outfs ]] ; then
#            out=$outfs
#            hadcat "$counted" | $catdiv "$sums" | catz_to "$out"
#        else
