#!/bin/bash
BLOBS=${BLOBS:-~graehl/blobs}
. $BLOBS/bashlib/unstable/bashlib.sh

usage() {
    cat << EOF
usage: $0 in(etrees) [out(pcfg events]

etrees are same format as input to extract (radu, heads, score 0.0)

format of output events:
LHS, TAB, CHILD1 CHILD2 ... CHILDN, TAB, count, TAB, sum(lhs count), NEWLINE

out is grouped by event.
EOF
    exit 1
}

main() {
        in=$1
        out=${2:--}
#        shift
#        shift
        [[ $in ]] || usage
        pre=${pre:-${in%.eng-parse}.}
        counted=${counted:-${pre}counted}
        sums=${sums:-${pre}lhs-sums}
        showvars_required in out counted sums
        showvars_optional infs pre
#        exit

        unset outfs

        iomr-hadoop "$in" "$counted" $d/pcfg-map $d/count.py

        save_infs=$infs
        unset infs

        iomr-hadoop "$counted" "$sums" $d/lhs-sums-map $d/count.py
        hadget "$sums"

        showvars_required out
        hadcat "$counted" | $d/cat-pcfg-for-divide "$sums" | catz_to "$out"
        previewf "$out"
    }

    main "$@"
